// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuTools-memory'
  | 'menuTools-monitor'
  | 'menuTools-startRecord'
  | 'menuTools-stopRecord'
  | 'pref-help'
  | 'pref-openMonitorOnStart'
  | 'pref-showMonitorIcon'
  | 'pref-title'
  | 'pref-updatePeriod'
  | 'prefs-title';
